# Generated by Django 6.0.5 on 2026-06-24 08:56

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_auditlog_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="righttowork",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="rtw_documents/",
                validators=[utils.validators.validate_upload],
            ),
        ),
        migrations.AlterField(
            model_name="wtroptout",
            name="agreement_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="wtr_optouts/",
                validators=[utils.validators.validate_upload],
            ),
        ),
    ]
