# Generated by Django 6.0.5 on 2026-05-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_acceptance_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gap_job',
            field=models.ForeignKey(blank=True, help_text='Link to the gap job accepted while this task was suspended.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_tasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='resume_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='suspend_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
