# Generated by Django 6.0.5 on 2026-05-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_gap_job_task_resume_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='total_active_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative active time in seconds, excluding suspension time.'),
        ),
    ]
