# Generated by Django 6.0.5 on 2026-05-26 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_total_active_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Employee-reported completion percentage (0–100). Triggers smart nearby suggestions at >=80.'),
        ),
        migrations.AddField(
            model_name='task',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline by which the job must be completed (SLA). Used to block pauses and prioritise dispatch.', null=True),
        ),
        migrations.CreateModel(
            name='TaskActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('gap_started', 'Gap Job Started'), ('gap_completed', 'Gap Job Completed'), ('completed', 'Completed'), ('nearby_suggested', 'Nearby Job Suggested'), ('nearby_accepted', 'Nearby Job Accepted'), ('nearby_rejected', 'Nearby Job Rejected'), ('completion_pct', 'Completion % Updated'), ('sla_warning', 'SLA Warning Issued')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tasks.task')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
