# Generated by Django 6.0.5 on 2026-05-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_sla_completion_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='client_alternate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='client_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='client_contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='task',
            name='landmark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='required_spare_parts',
            field=models.TextField(blank=True, help_text='Comma-separated or list of spare parts needed.'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_tools',
            field=models.TextField(blank=True, help_text='Comma-separated or list of tools required.'),
        ),
        migrations.AddField(
            model_name='task',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='client_name',
            field=models.CharField(blank=True, help_text='Customer/client name.', max_length=200),
        ),
    ]
