# Generated by Django 6.0.5 on 2026-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_area_task_city_task_client_alternate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When employee accepted the task.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When push notification was sent to employee.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, help_text="When employee marked 'On The Way'.", null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_the_way', 'On The Way'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
