# Generated by Django 6.0.5 on 2026-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_add_on_the_way_status_and_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notification_sent_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='on_the_way_at',
        ),
        migrations.AddField(
            model_name='task',
            name='is_pushed_gap_job',
            field=models.BooleanField(default=False, help_text='True when admin explicitly pushed this task as a gap job to an employee who has a suspended task.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
