# Generated by Django 6.0.5 on 2026-05-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_add_is_pushed_gap_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reached_site_at',
            field=models.DateTimeField(blank=True, help_text="When the employee tapped 'I've Arrived' at the client location.", null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='travel_status',
            field=models.CharField(blank=True, choices=[('on_the_way', 'On The Way'), ('reached_site', 'Reached Site'), ('working', 'Working'), ('done', 'Done')], db_index=True, help_text='Journey phase for field tasks: on_the_way → reached_site → working → done', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='work_started_at',
            field=models.DateTimeField(blank=True, help_text="When the employee tapped 'Start Work' — distinct from task.started_at which is set by /start/.", null=True),
        ),
    ]
