# Generated by Django 5.2.15 on 2026-06-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
        ('tasks', '0012_task_blocking_reason_task_inventory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='service_request',
            field=models.ForeignKey(blank=True, help_text='The service request this job/task was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='service_requests.servicerequest'),
        ),
    ]
