# Generated by Django 6.0.5 on 2026-06-24 08:56

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_task_service_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tasks/end_photos/",
                validators=[utils.validators.validate_upload],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tasks/start_photos/",
                validators=[utils.validators.validate_upload],
            ),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="file",
            field=models.FileField(
                upload_to="tasks/attachments/",
                validators=[utils.validators.validate_upload],
            ),
        ),
    ]
