# Generated by Django 6.0.5 on 2026-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_taskchecklistitem_taskexpense_taskproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexpense',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskproduct',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='client_type',
            field=models.CharField(blank=True, help_text='Type of customer (e.g., VIP, Corporate, Regular)', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='preferred_time',
            field=models.CharField(blank=True, help_text='Preferred time of day for the task (e.g. 10:00 AM - 12:00 PM)', max_length=100),
        ),
        migrations.DeleteModel(
            name='TaskChecklistItem',
        ),
        migrations.DeleteModel(
            name='TaskExpense',
        ),
        migrations.DeleteModel(
            name='TaskProduct',
        ),
    ]
