# Generated by Django 6.0.5 on 2026-08-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_taskexpense_task_remove_taskproduct_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star – Poor'), (2, '2 Stars – Below Average'), (3, '3 Stars – Average'), (4, '4 Stars – Good'), (5, '5 Stars – Excellent')], null=True)),
                ('work_quality', models.PositiveSmallIntegerField(blank=True, help_text='1-5 quality score', null=True)),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, help_text='1-5 on-time score', null=True)),
                ('behaviour', models.PositiveSmallIntegerField(blank=True, help_text='1-5 behaviour score', null=True)),
                ('issue_resolved', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('feedback_token', models.UUIDField(blank=True, default=None, null=True, unique=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedback', to='tasks.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
