# Generated by Django 6.0.5 on 2026-08-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_customer_otp'),
        ('tasks', '0017_task_feedback_model'),
    ]

    operations = [
    ]
