# Generated by Django 6.0.5 on 2026-06-23 09:47

import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_bank_details_employee_currency_and_more'),
        ('time_tracking', '0006_timelog_tl_status_date_idx_timelog_tl_emp_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='time_logs/photos/', validators=[utils.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='clock_out_photo',
            field=models.ImageField(blank=True, null=True, upload_to='time_logs/photos/', validators=[utils.validators.validate_upload]),
        ),
        migrations.AddConstraint(
            model_name='timelog',
            constraint=models.UniqueConstraint(condition=models.Q(('clock_out__isnull', True)), fields=('employee',), name='unique_open_timelog_per_employee'),
        ),
    ]
