# Generated by Django 6.0.5 on 2026-07-22 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_primary_country_alter_region_code'),
        ('employees', '0010_employee_service_roles'),
        ('payroll', '0004_payrollrecord_extras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollgeneration',
            name='config_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Stores the EmployeePayrollConfig values at the time of generation'),
        ),
        migrations.CreateModel(
            name='PayrollGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_groups', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='payrollgeneration',
            name='payroll_group',
            field=models.ForeignKey(blank=True, help_text='Group this employee was part of when payroll was generated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_generations', to='payroll.payrollgroup'),
        ),
        migrations.CreateModel(
            name='EmployeePayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_share_pct', models.DecimalField(decimal_places=2, default=80, help_text='% of service revenue paid to employee', max_digits=5)),
                ('company_share_pct', models.DecimalField(decimal_places=2, default=10, help_text='% of service revenue retained by company', max_digits=5)),
                ('platform_fee_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('platform_fee_value', models.DecimalField(decimal_places=2, default=5, help_text='Platform fee — either % or fixed amount depending on platform_fee_type', max_digits=10)),
                ('pf_enabled', models.BooleanField(default=True, help_text='Provident Fund (12%)')),
                ('pf_pct', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('esi_enabled', models.BooleanField(default=True, help_text='ESI (Employee State Insurance 0.75%)')),
                ('esi_pct', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('tds_enabled', models.BooleanField(default=False, help_text='TDS (Tax Deducted at Source)')),
                ('tds_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('ot_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Overtime pay multiplier (e.g. 1.5 = time-and-a-half)', max_digits=4)),
                ('daily_ot_threshold', models.DecimalField(decimal_places=2, default=8, help_text='Hours per day before daily OT kicks in (US CA/AK)', max_digits=5)),
                ('weekly_ot_threshold', models.DecimalField(decimal_places=2, default=40, help_text='Hours per week before weekly OT kicks in (US 40h, UK 48h)', max_digits=5)),
                ('service_split_enabled', models.BooleanField(default=False, help_text='Enable service revenue split for US/UK employees too')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Enable/disable individual payroll features per employee')),
                ('pay_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('weekly', 'Weekly')], help_text='Override the company default pay frequency for this employee/group', max_length=20, null=True)),
                ('custom_deductions', models.JSONField(blank=True, default=list, help_text="[{name, type: 'fixed'|'percentage', value, enabled}]")),
                ('custom_bonuses', models.JSONField(blank=True, default=list, help_text="[{name, type: 'fixed'|'percentage', value, enabled}]")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_configs', to='companies.company')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_configs', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='payroll.payrollgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('company', 'employee'), name='unique_payroll_config_per_employee')],
            },
        ),
    ]
