# Generated by Django 6.0.5 on 2026-08-04 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_reschedule_rejection_strategy'),
        ('employees', '0011_alter_employee_payroll_group'),
        ('payroll', '0005_payrollgeneration_config_snapshot_payrollgroup_and_more'),
        ('service_requests', '0016_alter_reschedulerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_share_percent', models.DecimalField(decimal_places=2, default=80.0, help_text='% of service revenue paid to employee', max_digits=5)),
                ('company_share_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='% of service revenue retained by company', max_digits=5)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='% platform fee', max_digits=5)),
                ('platform_fee_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('platform_fee_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed platform fee amount if platform_fee_type is FIXED', max_digits=10, null=True)),
                ('pf_percent', models.DecimalField(decimal_places=2, default=12.0, help_text='PF deduction % from employee share', max_digits=5)),
                ('esi_percent', models.DecimalField(decimal_places=2, default=0.75, help_text='ESI deduction % from employee share', max_digits=5)),
                ('tds_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='TDS deduction % from employee share', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_payroll_configs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('esi_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_credit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREDITED', 'Credited'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='service_requests.servicerequest')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='employees.employee')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='companies.company')),
                ('payroll_config', models.ForeignKey(help_text='Snapshot reference to config active at calculation time', on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='payroll.payrollconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_balance', to='employees.employee')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_wallet_balances', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('org', 'employee'), name='unique_wallet_balance_per_org_employee')],
            },
        ),
    ]
