# Generated by Django 6.0.5 on 2026-07-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='service_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
