# Generated by Django 6.0.5 on 2026-07-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_service_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='service_roles',
        ),
    ]
