# Generated by Django 6.0.5 on 2026-07-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employee_service_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='service_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
