# Generated by Django 6.0.5 on 2026-07-22 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_service_roles'),
        ('payroll', '0005_payrollgeneration_config_snapshot_payrollgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payroll_group',
            field=models.ForeignKey(blank=True, help_text='Payroll group for bulk config — individual config overrides this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payroll.payrollgroup'),
        ),
    ]
